### ISSUE TITLE
ERC20 token transfer on transaction page + better JSON data view

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#105]
- [x] Users should be able to see the amount of ERC20 tokens transfered on the transaction page
- [x] Users should be able to see the amount of ERC20 tokens transfered on the transactions page if there is no TLOS value 
- [ ] JSON viewer for logs & internal transaction needs UI/UX work

**Comment by EJSG** [comment]
@tomtomcrypto just gathering info on existing issues, what's the state of this?
@karynemayer for tracking

**Comment by karynemayer** [comment]
@tomtomcrypto we should remove the JSON viewer from this task

**Comment by tomtomcrypto** [comment]
That is actually done and in production
