### ISSUE TITLE
Tabs don't navigate properly

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/teloscan#107]
## Overview

Routing to conditional tab should be handled.

## Steps to reproduce

1. Go to https://www.teloscan.io/address/0xfa9da51631268a30ec3ddd1ccbf46c65fad99251#contract
2. See the empty screen with no data and no indication that this is not supposed to exist

## Current behavior

The page does not redirect when direct-loading a conditionally valid tab, resulting in a blank screen

![Image](https://user-images.githubusercontent.com/2939354/194115138-cd0c8cd1-5091-479c-a5f1-ec093805a69e.png)

## Expected behavior

Redirect the user to the Transactions tab

**Comment by EJSG** [comment]
see recent work by me to update hash handling on older pages:
https://github.com/telosnetwork/teloscan/blob/ea44ebf27103e591fd09d4e5cfcabedfce3ea145/src/pages/staking/Staking.vue#L84

also in the same PR I'll fix an edge case i overlooked, on the address page, the contract tab is conditionally hidden; going to an address page which is not a contract with the `#contract` hash will result in invalid tab being selected, eg.
https://www.teloscan.io/address/0xfa9da51631268a30ec3ddd1ccbf46c65fad99251#contract
