### ISSUE TITLE
Resolve lingering dependabot alerts

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#113]
A lot of the remaining alerts are related to the quasar version. Should be able to upgrade minor version and upgrade major version at a later date.

- upgrade @quasar/app from 2.3.1 to 2.4.0: https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v2.4.0

**Comment by EJSG** [comment]
@donnyquixotic checking in, is this still needed after recent upgrades?
