### ISSUE TITLE
Text overflow on login modal

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#124]
## Steps to reproduce
1. Go to https://teloscan.io
2. If you are logged in, log out
3. Click on Connect Wallet in the upper right corner

![Bildschirmfoto 2022-09-07 um 14 51 36](https://user-images.githubusercontent.com/11837820/188982755-ded4e5e6-3ee7-4ed4-bc5d-55ce14c69cc0.png)

## Current behavior
Modal pops open with the metamask logo and text overflowing

## Expected behavior
Text should not overflow its container; it should be centered and legible

**Comment by EJSG** [comment]
Already completed at some earlier date

**Comment by tomtomcrypto** [comment]
Yeah I did that in #153
