### ISSUE TITLE
Audit unsafe BigNumber casts

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#133]
## Overview
Presently, there are places in the code where `BigNumber`s are treated like javascript numbers, resulting in unintentional loss of precision, as well as unexpected complexity in modifying/understanding existing code. It is unclear how frequently these instances are visible to the user, but it is undesirable to be losing precision as values are passed around from component to component. Ethers documentation notes that values greater than `0.009 eth` begin to produce rounding errors when EVM values are not handled correctly
See `ethers` documentation for more information: https://docs.ethers.io/v5/single-page/#/v5/api/utils/bignumber/-%23-BigNumber--notes-safenumbers

## Steps to reproduce
N/A

## Current behavior
unsafe casts in code look like,
```js
getGasFee() {
    return (
        (this.trx.charged_gas_price * this.trx.gasused) /
        1000000000000000000
    ).toFixed(5);
},
```
(from `Transaction.vue`)

## Expected behavior
Code should use `BigNumber` any time wei or eth is being handled. Every instance of this should be searched and noted. Its location in the UI should be noted (and placed--along with notes on how to test it--in the pull request) and then the code should be refactored. Additionally:
- the constant `WEI_PRECISION` should be used in place of any magic string or number where manual manipulation is required
- `utils#formatBN` should be updated to prevent unsafe casts; this util can be used in most of the offending places
    - util should be renamed to `formatBn` to follow camelcase convention
- every example should be evaluated for the nullability of the number as well; if it is at all possible for a variable to be nullish, it should be declared as `BigNumber.from(someValue ?? '0')`

example refactor:
```js
getGasFee() {
    const gasPriceBn = BigNumber.from(this.trx.charged_gas_price);
    const gasUsedBn = BigNumber.from(this.trx.gasused);
    return formatBn(gasPriceBn.mul(gasUsedBn, WEI_PRECISION, 5);
},
```

**Comment by karynemayer** [comment]
At this time, we're not sure how much it impacts users currently, so we're going to approach this by saving a time slot to investigate this impact:

⌛ up to 2 days
