### ISSUE TITLE
sTLOS UAT improvements and requests

### ISSUE THREAD

**Issue by Kersten-TCD** [telosnetwork/teloscan#145]
The combined feedback of the UAT feedback is covered here.

**User Interface and mobile experience**

- [x] On mobile the background "cuts" through the main info. Chrome on Android.

![2022-09-14 15 27 04](https://user-images.githubusercontent.com/39388424/190197060-4efdde06-672e-4ffb-9b52-edccfe05f30d.jpg)

- [x] Tooltip on mobile browser can hardly be read as users need to touch while trying to read. Please verify change of mouse-over for mobile devices.

- [x] Verify precision of values in all modals 17 shown vs. 18

![Bildschirmfoto 2022-09-14 um 18 09 57](https://user-images.githubusercontent.com/39388424/190206599-28a582a4-a783-4ea0-97b7-4828947f1554.png)

- [x] Revise tooltip for balance in stake modal: "Click to stake entire wallet balance. **Balance displayed is reduced by 1 TLOS to keep your account actionable.** Precise Balance....."

![Bildschirmfoto 2022-09-15 um 10 27 56](https://user-images.githubusercontent.com/39388424/190355446-8ef7e876-e7df-43e1-9a5f-d36b6cee0847.png)

- [x] Revise text size of all tooltips for the entire sTLOS interface (if this change impacts OBE entirely, this will also be ok) to be better readable by 2 or 3 pt, text is very hard to read.

- [x] Revise introduction text in staking modal: "Staking your TLOS to sTLOS grants you access to a steady income and various DeFi applications, further increasing yield. As the reward pool increases, the TLOS to sTLOS conversion rate will change over time. Therefore, the amount of sTLOS received is smaller than the staked TLOS. Rewards will be auto-compounded. No further action is required. "

![Bildschirmfoto 2022-09-15 um 11 29 33](https://user-images.githubusercontent.com/39388424/190369309-8cd60546-75fb-4ed6-9980-9bbda8af41a1.png)

- [x] Verify if text for "Staked Successfully with transaction ID:" can be displayed before MetaMask confirmation is displayed. The confirmation would proof the exceptional speed of tEVM. To be considered based on overall user experience since popup might require further user interaction/click. (optional)

- [x] Balance in staking modal is not updated after successful staking of TLOS. Interface should refresh balance after transaction.

![Bildschirmfoto 2022-09-15 um 10 35 16](https://user-images.githubusercontent.com/39388424/190356744-ec2d9e9e-4864-4b04-a56c-ddf189a3e625.png)

- [x] Positions in claim modal not updating, browser refresh is required to see newly staked positions. Add auto-refresh so positions and balances update without further user interaction (this was implemented in earlier stage as far as I recall)

- [x] Revise text in claim modal for the case that no unstated positions are available. Change "No Data available" to "No claimable positions"

![Bildschirmfoto 2022-09-15 um 11 35 07](https://user-images.githubusercontent.com/39388424/190370413-8514588b-2e6a-4186-a110-0bf85e789f50.png)

- [x] "Burger menu" does not collapse when clicking in frame or input fields inside any modal. When changing modal (staking to unstaking) menu will collapse. (optional)

**Comment by EJSG** [comment]
To clarify some terminology, so we are all aligned:
- **modal** is used to refer to a window which pops up over other content on-screen, such as when you are on the stake form and click "Stake TLOS" (the text within begins with, _"Continuing will stake TLOS in exchange for sTLOS. sTLOS can be redeemed for TLOS at any time using the Unstake tab."_). modals generally block all other actions on a page until they are dismissed
- **tab** is used to refer to page subnavigation, such as allows you to move between Stake, Unstake, and Claim on the staking page
- **tooltip** is used to refer to the text box which appears on mouse hover / mobile tap of a particular element (usually an "i" info icon in our application), such as the one which appears when hovering on the info icon next to APY. The _tooltip_ in this case is the gray box which appears, containing the definition of APY on Telos


I don't want to edit the Issue text just in case I am misinterpreting things, @Kersten-TCD would you mind checking the acceptance criteria against the terms listed above? e.g. if I am reading correctly,
 > Revise text size of info-boxes to be better readable by 2 or 3 pt, text is very hard to read.

would be updated to,

_Revise text size of_ **tooltips** _to be better readable by 2 or 3 pt, text is very hard to read._

**Comment by Kersten-TCD** [comment]
@EJSG issue updated for clarity.

**Comment by Kersten-TCD** [comment]
@EJSG I think all of this is resolved, can we close this?
