### ISSUE TITLE
Tooltip doesn't fade away on desktop

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#164]
The tooltip doesn't fade away when you mouse out on desktop

![image](https://user-images.githubusercontent.com/5913758/192414241-7701de99-4f33-4617-9fad-c090adb58035.png)

**Comment by tomtomcrypto** [comment]
Seems related to changes here: https://github.com/telosnetwork/teloscan/blob/master/src/boot/q-component-defaults.js

**Comment by tomtomcrypto** [comment]
Yeah, it is finding my chrome browser to be a touch device when it isn't :(

**Comment by tomtomcrypto** [comment]
Ok got it, need to replace

```
    const isTouchDevice = ( 'ontouchstart' in window ) ||
        ( navigator.maxTouchPoints > 0 ) ||
        ( navigator.msMaxTouchPoints > 0 );
```
with

```
    const isTouchDevice = (window.matchMedia('(pointer: coarse)').matches);

```

then it works on Chrome, need to check support tho

**Comment by tomtomcrypto** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia seems good

**Comment by tomtomcrypto** [comment]
https://quasar.dev/options/platform-detection

**Comment by tomtomcrypto** [comment]
Yeah that works too, at least on Chrome
```
import { QTooltip, Platform } from 'quasar';

...

const isTouchDevice = Platform.has.touch && Platform.is.mobile;
```

**Comment by tomtomcrypto** [comment]
this would rule out desktop with touchscreens tho, but the has.touch seems to have false positive for desktop...

**Comment by tomtomcrypto** [comment]
```
// Method 3: Modernizer way
function isTouchDevice() {
    var prefixes = ' -webkit- -moz- -o- -ms- '.split(' ');
    var mq = function(query) {
        return window.matchMedia(query).matches;
    }

    if (('ontouchstart' in window) || window.DocumentTouch && document instanceof window.DocumentTouch) {
        return true;
    }

    // include the 'heartz' as a way to have a non matching MQ to help terminate the join
    // https://git.io/vznFH
    var query = ['(', prefixes.join('touch-enabled),('), 'heartz', ')'].join('');
    return mq(query);
}
```

**Comment by EJSG** [comment]
christ that was a lot more complex than i originally thought, nice going
