### ISSUE TITLE
Fix APY calculation

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/teloscan#166]
https://github.com/telosnetwork/teloscan/blob/a643d2d24c522a8796c1483ce849cee400322b42/src/pages/staking/staking-utils.js#L98

This APY formula was ported from the contract and the contract had a bug where the total at the end of this line only considered REX.  It should be `const balanceRatio = rexTotal.eq(0) ? -1 : stlosTotal.times(fixedRatio).div(rexTotal + stlosTotal);`

**Comment by poplexity** [comment]
Also, need to check for OBE and how it calculates APY since it will likely also have this same issue.

**Comment by tomtomcrypto** [comment]
Fixed by #169
