### ISSUE TITLE
Read/write interface doesn’t handle arrays properly

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/teloscan#171]
## Overview
When interacting with the contract function interface, some/all array arguments will incorrectly produce an error. 

## Steps to reproduce
1. ensure you have a wallet connected
2. Go to https://www.teloscan.io/address/0xb9239af0697c8efb42cba3568424b06753c6da71#contract
3. Click on the **Write** tab
4. Scroll down to the method `swapETHForExactTokens`
5. enter values shown in the screenshot below (any address can be used)
6. note the error 

<img src="https://user-images.githubusercontent.com/2374993/194441514-99e40b33-97e8-4d3b-a803-081832edebeb.png" width="300">

## Current behavior
Method call fails with the error `Result (uint256[]): invalid value for array (argument="value", value="[0x160505F3dfD1cb58B91e322c828Ae0F74c043c3C]", code=INVALID_ARGUMENT, version=contracts/5.7.0)` 

**Note:** need to determine a set of valid values that _should_ work, not just error in a different way

## Expected behavior
method should fail for a different reason, this error suggests an issue with parsing array type arguments (possibly only `address[]` in this case).
The fix for this should be tested to at least not break (or fix, if they're broken) the currently-implemented argument types, `uint256` and `uint256[]` **along with introducing** a working `address[]` and `address`. Implementation of other parameter types as well as improved error UI will be handled in #104 

additionally:
- for each of the four types, helpful error messaging should be printed in below the form input as a stopgap until UI work in #104 is completed. This validation should occur on blur and after a paste from clipboard
- a disclaimer should be added at the top of the ABI UI informing the user that certain data types are yet to be implemented, and will be added soon

**Comment by poplexity** [comment]
![718703BD-A32A-4CBD-83CA-267FA475090E](https://user-images.githubusercontent.com/2374993/194103021-8dfaf70d-552b-45d1-ab8c-61dce164b16f.jpeg)

**Comment by EJSG** [comment]
this issue is a subset of https://github.com/telosnetwork/teloscan/issues/104

**Comment by EJSG** [comment]
Need a little more info to work on this, especially steps to reproduce

https://github.com/telosnetwork/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by poplexity** [comment]
You can reproduce on [this](https://www.teloscan.io/address/0xb9239af0697c8efb42cba3568424b06753c6da71#contract) contract using the function `swapETHForExactTokens` and the parameters as noted in the screenshot ![image](https://user-images.githubusercontent.com/2374993/194441514-99e40b33-97e8-4d3b-a803-081832edebeb.png)

**Comment by EJSG** [comment]
note: the PR for this issue covered parameter types `address`, `address[n?]`, `bool`, `bool[n?]`, and `string`
