### ISSUE TITLE
Make Staking link more prominent

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#174]
There have been several requests to make the staking link more prominent, rather than being hidden in the hamburger menu. This would necessitate a refactor of the header, possibly including moving the dark mode toggle to the hamburger menu.
We should also consider updating the search bar presentation as a part of this--we ought to have a header with good RWD after issue completion

**Comment by donnyquixotic** [comment]
Duplicated, migrated your comment to https://github.com/telosnetwork/teloscan/issues/175
