### ISSUE TITLE
Mobile clients can't sign in with metamask

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#202]
## Overview

You can't connect using metamask using any mobile browser. 

## Steps to reproduce

1. Go to teloscan.io
2. Click on connect wallet
3. Click on the metamask logo in the modal 

## Current behavior

Nothing happens

## Expected behavior

A metamask prompt should appear to sign in.
Once logged in using metamask mainnet, if you join a testnet address, you should also be prompted to switch the network.

**Comment by tomtomcrypto** [comment]
That is actually normal behaviour as far as I know. To use metamask on mobile you have to use their in-app browser.

**Comment by EJSG** [comment]
@tomtomcrypto It is true that it's not injected, however it seems metamask does have a suggested workflow for enabling dapps to use a js library (or possibly deeplinking to metamask native app) to sign in and perform actions, https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

**Comment by tomtomcrypto** [comment]
Was never able to make it work when I tried, they say the provider eventually gets injected but in my experience it never does, at least not in Chrome. Maybe they made it better since tho, been a while.

**Comment by EJSG** [comment]
You are totally right, thanks @tomtomcrypto. It seems like we could reimplement all `provider` calls using their relay API but that seems unwise for several reasons. I'll go ahead with deeplinking
