### ISSUE TITLE
Use more permanent URL for icon

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/teloscan#204]
## Overview

Should reference the image from somewhere more permanent in case we ever change the image name/path on teloscan we don’t break everyone’s metamask.  

https://github.com/telosnetwork/teloscan/blob/555e736b89291491a3f1d3730d82f8d370799ea0/src/pages/staking/staking-utils.js#L128

## Acceptance criteria

- Grab images from a single source of truth

## Technical considerations

We have a repo for [images](https://github.com/telosnetwork/images), or could put it in the [token-list](https://github.com/telosnetwork/token-list) repo

## Tasks

- [x] Add the sTelos logo to the images repository
- [x] Use the raw link from github

**Comment by tomtomcrypto** [comment]
Fixed in #227
It didn't actually work before that, it wasn't adding any icon to stlos in metamask
