### ISSUE TITLE
Token tab balances too precise

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#228]
Token tab on the /account page should only show 3 decimal places (possibly including more precision on hover)

https://www.teloscan.io/address/0x160505F3dfD1cb58B91e322c828Ae0F74c043c3C#tokens -> STLOS

![Image](https://user-images.githubusercontent.com/11837820/200413674-c89d3ad5-5f87-491b-9bd3-6bbe2c2af772.png)

## Acceptance criteria
- The tokens precision should be capped at 4 decimals
- The tokens full number should be displayed as a tooltip
- If its zero, we'll continue to show `0.0`
- Trim zeros whenever possible

**Comment by tomtomcrypto** [comment]
![image](https://user-images.githubusercontent.com/5913758/200618912-e474baf3-6cc0-48c1-aef6-4197775f702e.png)

**Comment by tomtomcrypto** [comment]
Fixed in #227
