### ISSUE TITLE
Investigate adding other EVM wallets

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#247]
## Overview
We would like to add more wallets and prioritize their integration accordingly. 

## Acceptance criteria
- Investigate how we could add Wallet Connect
- Wallet connect should enable the user to use Teloscan just as much as Metamask
- Issues created for the successful implementation with required references for the implementation

### Out of scope
- Any feature within these wallets should not be considered for our support

## Time slot
2 days

## Notes
- WalletConnect integration captured in #310

**Comment by poplexity** [comment]
Rainbowkit is a great tool for react, could try https://github.com/wobsoriano/vagmi which is a vue port of wagmi which is the parent project of rainbowkit

**Comment by karynemayer** [comment]
@poplexity could you add more information on the acceptance criteria for adding a new wallet? What is the minimal functionality we should provide?

Which are the known commonly used wallets that would be most easy to implement? It would be just Wallet Connect?
