### ISSUE TITLE
Better user navigation with the header

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#262]
## Overview
This issue aims to provide better navigation through the header on teloscan. 

## Acceptance Criteria
- Search bar should have highest affordance other than the burger menu
- Light/dark theme toggle should be in the dropdown menu
- Hide Connect Wallet from unsupported browsers (ie. mobile browsers outside of metamask app built-in browser)

_Originally posted by @EJSG in https://github.com/telosnetwork/teloscan/issues/260#issuecomment-1355624163_

**Comment by EJSG** [comment]
See also: https://github.com/telosnetwork/teloscan/issues/175

**Comment by tomtomcrypto** [comment]
Connect Wallet is supported by all browsers. It is just the Metamask part that isn't. But Anchor should work for example.

**Comment by EJSG** [comment]
@tomtomcrypto Karyne is designing a new header overall. connect button acceptance criteria is out of date

**Comment by EJSG** [comment]
@tomtomcrypto also metamask login already deeplinks to metamask app on mobile browsers

**Comment by karynemayer** [comment]
Will be addressed in https://github.com/telosnetwork/teloscan/issues/274
