### ISSUE TITLE
sTLOS staking login message with wrong width

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#280]
* Adjust the login message container margin to follow the header's
* Adjust the warning icon to stay on the left side of the container on all screen sizes

<img width="758" alt="Screen Shot 2023-01-04 at 16 35 49" src="https://user-images.githubusercontent.com/2939354/210675725-bb679550-06d7-43bb-a345-3874b72da69f.png">
<img width="380" alt="Screen Shot 2023-01-04 at 16 37 08" src="https://user-images.githubusercontent.com/2939354/210675840-1ef73e8a-6f48-40e8-9a5e-eb55b6ca92bd.png">

**Comment by karynemayer** [comment]
@Kersten-TCD could you provide more information on this? I copied from your feedback on [v1.1.0-rc](https://github.com/telosnetwork/teloscan/pull/275)

**Comment by Kersten-TCD** [comment]
Minor Design change ;-)

![Bildschirm­foto 2023-01-05 um 11 24 02](https://user-images.githubusercontent.com/39388424/210758131-290019b2-859e-4aca-92b1-f7aa05ff35c0.png)
