### ISSUE TITLE
ERC721 transfer pagination is inconsistent

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#284]
## Overview
There are a few issues when displaying ERC721 transfers:

* ERC721 transfers only show the first three transactions at first click, requiring the user to expand to 50 to show all. 
* Load time for page 2 with further 50 transactions is extremely slow. 
* Page 3 shows "no data available" for account with 113 total ERC721 transactions.
* ERC721 and ERC20 page transfers, when clicking on last page/transaction icon. "no data available" is displayed

### Notes
Please check displayed # of records, ERC20 and ERC721 page show same number, I assume filter by ERC might be the issue. ERC1155 shows different/correct number
![image](https://user-images.githubusercontent.com/2939354/210677689-f2b7d8f1-6d84-4a83-9599-c4466bd836ce.png)

## Acceptance Criteria
* ERC721 transfers should show the number of results indicated in _Records per page_
* Pagination for ERC721 and ERC20 tokens should accurately consider the total number of transfers and properly paginate the items

**Comment by tomtomcrypto** [comment]
All transfers are inconsistent. We need the indexer to solve it.

**Comment by tomtomcrypto** [comment]
Solved by #368
