### ISSUE TITLE
contract abi JSON file upload & parsing for unverified contracts

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#290]
**Description**
For unverified contracts, we allow pasting the abi into the input for parsing. We should allow uploading the json file and parsing accordingly to mitigate copy/paste errors and provide an easier alternative for large JSON files. 

**Solution**

- [ ] add 'Upload' button which prompts file explorer to select json file
- [ ] parse file
- [ ] generate ABI (same functionality as copy & paste)
- [ ] handle any parsing error(s)

**Comment by Viterbo** [comment]
I close this issue since it was addressed in https://github.com/telosnetwork/teloscan/pull/318
