### ISSUE TITLE
Text on top of APY

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#330]
## Overview
Depending on the size of the text, it gets on top of APY. With the addition of different languages, we should consider larger size texts.
![Screenshot 2023-01-23 at 10 45 31](https://user-images.githubusercontent.com/2939354/214124107-dc2701e4-c484-42eb-9052-cd1d85669d4e.png)

## Acceptance criteria
* The text grows horizontally up to 60ch to 80ch
* The text grows vertically before reaching the APY icon

**Comment by tomtomcrypto** [comment]
Fixed in #368
