### ISSUE TITLE
fixing broken UI components caused by long non-english texts

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/teloscan#343]
# Description

The incorporation of the i18n library has allowed us to have multiple language translations. This new texts some times are shown in smaller places than the actually needed for the english version. In those cases, the UI cets broken in unexpected ways:

Here's is a list of known issues:
- https://github.com/telosnetwork/teloscan/issues/342
- https://github.com/telosnetwork/teloscan/issues/330

If you detecto another one, please create a separated issue and then add it to the list.

**Comment by tomtomcrypto** [comment]
Both problems fixed in #368, don't see other ones
