### ISSUE TITLE
Error notification appears when navigating through transactions

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#357]
## Overview
When navigating through transactions fast enough, you get the following errors:
<img width="561" alt="Screenshot 2023-02-13 at 15 06 10" src="https://user-images.githubusercontent.com/2939354/218595464-f2b1de48-5e79-44b6-a274-d22b071d28cd.png">
<img width="1334" alt="Screenshot 2023-02-13 at 14 56 06" src="https://user-images.githubusercontent.com/2939354/218595470-9f8d78ce-73d2-4acc-b3de-e98990ef6010.png">

##### Easy 
1. Change to 50 transactions per page
2. Move to the next page without waiting too long
3. See the error

##### Expert
1. Change to 10 transactions per page
2. Move to the next page as quickly as you can
3. See the error

### Acceptance criteria
* The error should not appear 
* `0 TLOS` should be used to indicate zero TLOS

**Comment by pmjanus** [comment]
Old version issue
