### ISSUE TITLE
Download transaction history as csv file

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#380]
**Temp blocked, waiting for API update per Tom**

**Being addressed in [this PR](https://github.com/telosnetwork/teloscan/pull/517)**

**Description**
Add ability to download transaction history for a given account in csv format:

# Acceptance Criteria
Add ability to download transaction history for a given account in csv format
- Include option to download by date range.
- Include option to download by block range.

- Once user inputs date/block range and type of transaction with a successful captcha, display a message saying: Your download is being prepared. (while it is loading). Then show download file save dialog.
- If the download takes longer than 60 seconds, throw an error and display a message:  Your request has timed out, please select a shorter date range or try again.

- For csv exports we want to export the same data fields as etherscan to help users integrate this csv into existing tools.

- Transactions:
Txhash | Blockno | UnixTimestamp | DateTime (UTC) | From | To | ContractAddress | Value_IN(TLOS) | Value_OUT(TLOS) | TxnFee(TLS) | Status | ErrCode | Method

- ERC-20:
Txhash	Blockno	UnixTimestamp	DateTime (UTC)	From	To	TokenValue	USDValueDayOfTx	ContractAddress	TokenName	TokenSymbol

- ERC-721 & ERC-1155:
Txhash | Blockno | UnixTimestamp | DateTime (UTC) | From | To | ContractAddress | TokenName | TokenSymbol | Token ID | Type | Quantity

**Note**
Fetch data from indexer
Base the flow on existing etherscan solution

**Comment by pmjanus** [comment]
We want to handle long download periods. Limit the time spent processing the request and serving it. So if it takes longer than x amount of time we can display a message to the user to select a smaller time frame.
If the time frame is one day then we can limit it to a minute.

Improve UX so that when the download is being processed user sees: Your download is being prepared.
If timeout display: Your request has timed out, please select a shorter date range or try again.

For csv exports we want to export the same data fields as etherscan to help users integrate this csv into existing tools.

**Comment by rozzaswap** [comment]
Ensure can download more than 100 transactions - expectation is 10,000

**Comment by tomtomcrypto** [comment]
## TRANSACTION

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transactions/csv?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000`

### ALL TYPES

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000`

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000&types=erc20,erc721,erc1155`

### SINGLE TYPES

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000&types=erc20`

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000&types=erc1155`

`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000&types=erc721`

### NFT TYPE
`/export/0x46Ce46951D12710d85bc4FE10BB29c6Ea5012077/transfers?captcha=10000000-aaaa-bbbb-cccc-000000000001&endBlock=400000000&startBlock=300000000&offset=1000&types=erc721,erc1555`

**Comment by Viterbo** [comment]
What am I doing wrong? @tomtomcrypto, can you correct me here?

I'm calling this exact HTTP GET:

https://api.teloscan.io/v1/export/0x7e5e168D68905DEE14EDDef5C596580e227Acb4F/transactions/csv?captcha=P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hadwYXNza2V5xQVewchk_v8bPATcGrADN-BH31EvG-Mr-1k8tGYxiG7n007Ek5Z-K8JS1lIXY-etoHA4SdYRiD_C2K3BjfMdJzL6bmI2Jw1ZR-sAa1JTksnSCLNNAk3zWsRLJY2LX5Eve5veuNdoSXdKCHUXMrSHt-YqSCE8s3MoQJ4z321bTDuSSBx91WWJI_Uswxfk2w_E9Jdxew745xsmPtWTdLdozlQBa2YqZ0UnvO66-qsjxMlBDdE5dDiSan9cZpcb4TmHJdTr6lcRu6jHT2J96ZCgEceg1KA5exuzNHaVwY17034V5pcxL0zky2u49D2Eyl24cF2OXwoDN-IotXDNN83lpcv6kntqZd--8WV_EwBOwqSC_5cMxgAoOVB75sf_bNSUrhcAS-h3Mo_RosOyYix3gaTykXXEsz3b8g23pzhla8u5b6cibqAFww3ihhsQm5m1D0s5QtXhKwcQHb5deMlDcumkQTgwAUSn-ioTODj0aW3BBJfaSbd1HDq-XC5Be4ze4S4AHRPHhz-k8q2kpEMld_dEsKuzDg7iP9IuMUDnfomEHGrBBXCGnW6gdjk3zx9G5W8pJ0j-22Y7wu0Dt1jrxdKCnEiQyNM5mu_mz3FNPNIvrc0P_Rf6JZK529LQ1_hL0UlnJPjd1ypad_1W9aOfZ6n9xmqu2_LfLwi-xEAjkrjcc_HvgEWWe00VC3PNJ1eDlAEYyTpZ1FDvGYpQdVsjYIm78vUyvb40xpMLzieI0-AmcxM9qYhkK7g9sct_RP2ezU695ESI47DtCJDYHYUy_sqnoTINBbi9OvOUPSZsDX_2dJMSTY2sttHPzx-xEHIP_QnbNiSDU1E85-6OTZcC_Cwd1kjWJ4ISHqRqQ1xCSzcjbhhseEeD0ulq-lJ3A5tNvLXImtoun8o6wKUf_F0hflavnGggT0yBWGFQr02nf7zQ8RCz2S9tN-sw4KV5tryrfaosa0RyiQHU3_OGFunjozvk5TJXuhTEloXQeiZV06fColfURchbYowcPsVPsFQZgZFZlTdlCpHx42UXeHPK1UfbdxJuUsdSLbPnRvcXR4sqI3_OhvWgo7Dz-M5L1rkZEO2fpNuoQfQqwcEB-EbmuRCx24hVKL3Ad4O-xfjl5uef4B5mijODcQkh9qVhfp9ItNvDN84KXN4vkwhisfuFQRLZ8YLyP30hg3_sOQfceaJC5tzJtTqjVHMcFZH3Lc9F09e61ysA-oQ77-IzQZ6ufRQgtmf8HBWfU3g047H2-25-JKA9wP71mxoFxa1C6e3w3Z_y0XMzVRJypBbaNXv6KOBTyjYboYVlHIX2zFR17ARvMw6vAL4WrGS1Q_lP2G2Be700lc3JJDmij7x0PJgWCqFDzjm5_KKXj-r9B0ay8USuEkIYkIwEjQZrp_cwgLJZlbJAY5OAIBaUIsPd_svA7l7FEIxcnedpjcIMkOLu5WyYmPqI2Y7CObSbof3jVVTDc6MzKMzZ1bRnWew5BLgU4hXO0Mr1io_Vc1CGzG3iHwSqau6TWa8W9jXpIYAPnXGQTuOAb-t0zB0RMPms44WqL4AY8PfXauefLhFctKQX4RBuu08zp1qV2NHmx7JSC-cKKrOu2xWCqcXZfs4m0FX8jH_UTz5UBFi7L_XMRf51mcZeKy_ZnOfB7Sc3JMKgdMI5hFZv2mtX7m0b1tp1txgzbLqzw1pzLml_VLLFAt7Vp9RtN6sDafa-lurgqrnh0WODlog2IgcL0QERmIKa4PfWerezYrme7tVnuaLIKlA5Yrn1ZGUqWAJC_PoE5tbVtIhXi15nq1AG2625QNHR8WXNxkjYrER25lWBb9gWbKN0lO3ro2V4cM5mH8QEqHNoYXJkX2lkzgRHJZGia3KoNDBlZTY2YjGicGQA.34JU8UBEJDsWOdvshL_NOr3k8alrsKS8F7Qo8yYYQuY&endBlock=336774396&startBlock=336758492&offset=1000

But I'm getting a 404 Error code.
![image](https://github.com/telosnetwork/teloscan/assets/4420760/8cbf055d-dffc-4ad5-a6fa-6e1c339654f6)

**Comment by Viterbo** [comment]
Also, The interface make the user select a date range but the endpoint expects a block number range (at least In the examples).
Can I pass a timestamp-based range? something like `&startDate=1711940400000&endDate=1712545200000` ?
![image](https://github.com/telosnetwork/teloscan/assets/4420760/171e3381-42ee-41d8-a4e9-4dbac7521ea4)

**Comment by rozzaswap** [comment]
@tomtomcrypto did you manage to look into this issue yet?
