### ISSUE TITLE
Header Address Display

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#388]
**Description**
Display the first few characters after leading '0x' instead of the just the trailing characters in the header address display like it does in MetaMask

**Screenshots**
current:
![image](https://user-images.githubusercontent.com/6848910/228703083-e33f5779-4f5f-4c03-b5e4-eda9696f48df.png)

MetaMask:
![image](https://user-images.githubusercontent.com/6848910/228703031-3d70a5b6-2375-4f08-b394-fb70ad7d3c3b.png)

**Comment by tomtomcrypto** [comment]
Fixed in #368
