### ISSUE TITLE
Incorrect Header Values Displayed for Non-Existent Addresses on Teloscan

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#409]
# Describe the bug
When searching for a non-existent address on Teloscan, the header values (balance and nonce) from the previously searched address are displayed instead of showing the correct values for a non-existent address.

# To Reproduce

Go to 'Teloscan'
Search for the address '0x4DaEFE5943b29940b0c55C1410A61633b9048e66'
Next, search for the non-existent address '0xA308816024FE8ddbCD202406b57F27AC580c42ce'
Observe that the balance and nonce values from the first address are still displayed
# Expected behavior
When searching for a non-existent address, the expected behavior should display a 0 balance and 0 nonce, similar to how Etherscan handles non-existent addresses. Etherscan shows 0 balance, 0 nonce, and no matching entries in the data tables. The displayed values should not be carried over from a previous search.

**Comment by tomtomcrypto** [comment]
Fixed in #368, close to confirm
