### ISSUE TITLE
Tokens tab enhancements 

### ISSUE THREAD

**Issue by iht76** [telosnetwork/teloscan#421]
Add checkbox or so, to display only tokens with balance > 0

Another type of view would be nice too. Using windows explorer analogy,  we now have large or "extra large icons", we need something like "list" or "details" type of view

**Comment by tomtomcrypto** [comment]
This is currently being implemented: https://deploy-preview-368--dev-mainnet-teloscan.netlify.app/address/0xe7209d65c5BB05Ddf799b20fF0EC09E691FC3f11#tokens
