### ISSUE TITLE
Responsive header text on transaction page

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#457]
**Describe the bug**
'Transaction Details' header text overlapping on mobile.

**To Reproduce**
1. Click on any transaction
2. See header text overlapped (see screenshot)

**Expected behavior**
Text should be responsive.  Display inline or line break so header text isn't overlapping. 

**Screenshots**
![image](https://github.com/telosnetwork/teloscan/assets/6848910/62ad351a-ecca-4932-beff-5923e76d119f)

**Comment by pmjanus** [comment]
Closed, not present anymore.
