### ISSUE TITLE
Feature Request - Allow searching for account name/address alias

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#48]
## Overview
Presently, users can only search for specific addresses in the search bar. Usability would be improved if users could search by account name/alias, eg. typing in `CharmDojo` would allow the user to go to `/address/0x730d2fa7dc7642e041bce231e85b39e9bf4a6a64`

## Acceptance criteria
- when typing in a non-address string into the search bar, a dropdown/card should appear prompting the user to go to the address page matching the query
    - clicking the dropdown/card should bring the user to the address page
    - by default, pressing enter (as opposed to clicking the new UI element) should first attempt to use the search query as an address; 
- a minimum of 3 character should trigger the alias UI element
- multiple results will need to be handled, eg. if the user types `TLO`, at least 2 results will match--`Wrapped TLOS` and `sTLOS`
    - there should be a maximum number of matches to prevent vertical overflow, or follow etherscan pattern of creating a scrollable container with a max height
- new UI element should be keyboard navigable; `tab`/`shift+tab` and `arrow up`/`arrow down` should allow the user to select the new UI element, and `enter`/`space` should go to the selected element; `esc` should hide the result(s)
- the dropdown menu should indicate tokens vs addresses vs contracts

## Technical considerations
- it _may_ be that the [currently in progress] indexer is required to do this mapping on the fly. See `TransferTable.vue` or `AccountAddress.vue` to determine if existing logic can be reused to this end

- refer to etherscan for their handling of this pattern for inspiration
- though WTLOS is used as an example, actual `/token` route is not yet implemented, and as such are out of scope here. navigating to WTLOS should go to the `address/` route for now, with token route implementation being added in #83

**Comment by pmjanus** [comment]
This is being handled in #800
