### ISSUE TITLE
Teloscan read and write contract should handle tuple parameters for contracts that require them.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#487]
### Teloscan Read and Write Contract Should Handle Tuple Parameters for Contracts that Require Them

---

**Problem:**

I've been trying out the prerelease Teloscan a bit and noticed a few issues.

Similar to the old version, it seems Teloscan can't handle tuple parameters when performing Read and Write operations on a contract. For example, for the contract `0x7D24DE60A68ae47BE4E852cf03Dd4d8588B489Ec` (AlgebraEternalFarming), the `getRewardInfo` function only retrieves a single field for `tokenId` (uint256) when the ABI looks like this:

```json
{
  "name": "getRewardInfo",
  "type": "function",
  "inputs": [
    {
      "name": "key",
      "type": "tuple",
      "components": [
        { "name": "rewardToken", "type": "address", "internalType": "contract IERC20Minimal" },
        { "name": "bonusRewardToken", "type": "address", "internalType": "contract IERC20Minimal" },
        { "name": "pool", "type": "address", "internalType": "contract IAlgebraPool" },
        { "name": "nonce", "type": "uint256", "internalType": "uint256" }
      ],
      "internalType": "struct IncentiveKey"
    },
    { "name": "tokenId", "type": "uint256", "internalType": "uint256" }
  ],
  "outputs": [
    { "name": "reward", "type": "uint256", "internalType": "uint256" },
    { "name": "bonusReward", "type": "uint256", "internalType": "uint256" }
  ],
  "stateMutability": "view"
}
```

Due to this limitation, it is not possible to call such functions from Teloscan.

---

**Acceptance Criteria:**

- Update Teloscan to handle tuple parameters correctly in both Read and Write operations.
- Ensure the system can parse and pass tuple components accurately when interacting with contracts.
- Add test cases to validate that tuple parameters are supported for all contract interactions.

**Comment by Viterbo** [comment]
Notes:

In the [IncentiveKey.sol](https://www.teloscan.io/address/0x7D24DE60A68ae47BE4E852cf03Dd4d8588B489Ec?tab=contract&subtab=source) file is defined the **IncentiveKey** struct as:
```solidity
struct IncentiveKey {
  IERC20Minimal rewardToken;
  IERC20Minimal bonusRewardToken;
  IAlgebraPool pool;
  uint256 nonce;
}
```
In the [AlgebraEternalFarming.sol](https://www.teloscan.io/address/0x7D24DE60A68ae47BE4E852cf03Dd4d8588B489Ec?tab=contract&subtab=source) is defined the **getRewardInfo** function as:
```solidity
function getRewardInfo(IncentiveKey memory key, uint256 tokenId) external view override returns (uint256 reward, uint256 bonusReward) {
    bytes32 incentiveId = IncentiveId.compute(key);
    Farm memory farm = _getFarm(tokenId, incentiveId);

    IAlgebraEternalVirtualPool virtualPool = IAlgebraEternalVirtualPool(incentives[incentiveId].virtualPoolAddress);
    (reward, bonusReward, , ) = _getNewRewardsForFarm(virtualPool, farm);
}
```
