### ISSUE TITLE
Feature Request - allow other ethereum providers

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#51]
**Is your feature request related to a problem? Please describe.**
wallet actions (such as add network) only target metamask but would work with other providers (such as coinbase wallet extension)

**Describe the solution you'd like**
let user choose from available providers if more than one

**Describe any alternatives you've considered**
check for metamask is an option first, if not, try to connect to another provider (if available)

**Additional context**
encountered when testing the 'add to Metamask' network dropdown option, the default behavior assumed metamask but if more than one provider is present, `window.ethereum.providers` contains the available options.

**Comment by EJSG** [comment]
@donnyquixotic It seems this may have already been completed, eg. `provider.js:48` handles coinbase wallet, which was committed after this ticket was created. Can you confirm ticket validity?

**Comment by karynemayer** [comment]
We're going to close this one because is too high level and we should separate it into each provider we want to support
