### ISSUE TITLE
Teloscan Homepage Redesign - Latest Transactions Table

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/teloscan#533]
Latest Transactions
- truncated hash
- time ago
- From contract name / address (truncated)
- To contract name / address (truncated)
- "X TLOS" where x is value, on hover, show "transaction amount" tooltip

**Comment by pmjanus** [comment]
[12:31 PM] Rorrie Crocker
I do wonder if it would look better with a more defined border on the tables, probably the same drop shadow in the submenus? Julio Peguero Ezra Sowden-Guzman
[12:35 PM] Rorrie Crocker
I just feel the tables blend into the background a little too much - we can talk about it later though for sure
