### ISSUE TITLE
Block route redesign

### ISSUE THREAD

**Issue by ezra-sg** [telosnetwork/teloscan#534]
the `/block` route should be refactored to show the following information _instead of_ a table of transactions:

- block height
    - tooltip: `Also called "Block Number". The block height represents the length of of the blockchain, increasing by one after the addition of a new block`
- timestamp
    - tooltip: "The time and date the block was produced"
    - in the format of `[clock icon] X unit ago (Mmm-DD-YYYY HH:MM:SS AM/PM +UTC)` e.g. `9 mins ago (Feb-16-2024 10:06:23 PM +UTC)`
- transactions
    -tooltip: "The number of transactions in the block. Internal Transactions are transactions which occur as a result of contract execution and include a TLOS value"
    - in the format of `X transactions and Y contract internal transactions in this block`, where "X transactions" is clickable and leads to `/txs?block={blocknum}`
- size
    - tooltip: "the amount of data in the block, determined by the gas limit"
    - `X bytes` where X is the size of the block, formatted using `toLocaleString()`
- gas used
    - tooltip: "The amount of gas used in the block"
    - show gas used, formatted using `toLocaleString()`
- gas limit
    - tooltip: "The gas limit for all transactions in the block"
    - show gas limit, formatted using `toLocaleString()`
- nonce
    - tooltip: "The value used during mining to achieve consensus on Proof of Work for the block"
    - show nonce
- hash
    - tooltip: "The hash of the block header"
    - show hash
- parent hash
    - tooltip: "The hash of the parent block"
    - show hash

**Comment by pmjanus** [comment]
Extra Data 
Hash
Parent Hash
Transactions Root
Nonce

We want to add Extra Data field, on ETH its just extra data you can add to the block.
In Eth and in Telos 2.0 extra data is part of block header so it is used in block hash, it provides uniqueness.
For this task: Display Extra Data, and make it Link to: native explorer/block/extravalue without 0x

Example:

The block page https://deploy-preview-542--teloscan-redesign.netlify.app/block/283797673?tab=overview

the field "extraData": "0x10ea68e25e45d59ba562c3c654b015e4360cdf744663baf518e739347dae7ec4",
verify: https://api.testnet.teloscan.io/v1/block/283797673

Link that clicking the extra value should give you: 
https://explorer-test.telos.net/block/10ea68e25e45d59ba562c3c654b015e4360cdf744663baf518e739347dae7ec4?page=1,10
