### ISSUE TITLE
Redesign Address Page Layout, Overview, Transaction, Token Transfer and Contract Tabs 

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#551]
## Layout ##
- Route /address/0x21701550c2a8dbf01a3562de440743964d84f5c9
- Address / Contract [AddressHex] copy button qr code icon

- Overview Card
- More Info Card with last transaction sent with tx hash and time ago and first txn sent and time ago

Tab selector
- Tabs:
    - Transactions, Token Transfers, Contract (if it is one)
    - Transactions Tab:

        - Latest 25 Transactions out of a total of X transactions for account (ordered from most recent to oldest:)

        - Rows: (get specifications from https://github.com/telosnetwork/teloscan/issues/535 )
                - ?
                - Txh Hash
                - Method
                - Block
                - Age
                - From
                - To
                - Value
                - Txn Fee

- Token Transfers
-  ?
- Txn Hash
- Method
- Age
- From
- To
- Value
- Token
- Contract (Checkmark icon if verified on top right of tab)
-  Code Tab
    - Contract Source Code Verified
    - Contract Name
    - Compiler Version
    - Optimizations Enabled
    - Other Settings
    - Contract Source Code (Language)
    - Outline Selector
        - Outlines the files and the functions on the files, has a Book Icon for Libraries, a Text Icon for contracts, labels them with a header and then has indented function names which you can click and navigate to the file or function on the page.
    - Copy Sourcecode icon, copy permalink icon, toggle fullscreen icon (expands the code display to have no scroll bar
        - Displays the code in a code display
    - Contract Security Audit 
        -  Display the audit and if not have a No Contract Audit Submitted with a Submit Audit Link next to it
    - Contract ABI  Export ABI Select with JSON Format and RAW/Text Format options, Copy ABI icon, Full screen icon
    - Contract Creation Code (CCC), Decompile Bytecode Link, Switch to Opcodes View
        - Display the CCC  
    - Deployed Bytecode
        - Display Deployed Bytecode
    - Swarm Source
        - Display Swarm Source
-  Read Contract Tab
-  Write Contract Tab
-  Proxy Tabs
- 

** Acceptance Criteria
- Maintain current functionality while changing look and feel to match the intended design
- Do not add any new information or features
- Merge NFT  tabs into one tab displaying all of the nft transfers, have a column for type of nft

**Comment by rozzaswap** [comment]
Also to include holders tab
