### ISSUE TITLE
Redesign Transaction Page - internal transactions tab

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#573]
Show latest 25 Internal txs for the address in a table with the following headers, the data in it should be similar to other page table content, keep the format identical where it can be.
Column headers:

Parent Txn Hash | Block | Age | From |   | To | Value

Have a button at the bottom that will lead to internaltxn table page (blocked until this is finished) filtered by address.

**Comment by rozzaswap** [comment]
initial work done ready for teloscan redesign mvp, needs another pass to streamline UI
