### ISSUE TITLE
Filter block transactions correctly to show ONLY transactions within the specified block on testnet

### ISSUE THREAD

**Issue by rozzaswap** [telosnetwork/teloscan#601]
Currently when viewing a block, and then the transactions in a block ALL transactions are displayed. We only should show transactions within the block.

**Comment by rozzaswap** [comment]
https://teloscan-redesign.netlify.app/block/289467002?tab=transactions

**Comment by Viterbo** [comment]
I'm closing this issue because this is not a front-end problem.
I explain everything in this [issue for the indexer](https://github.com/telosnetwork/teloscan-indexer/issues/198).

**Comment by pmjanus** [comment]
https://www.teloscan.io/block/342079942?tab=transactions

Can see it happening here, I don't see the query for txs include the block number on query params.
