### ISSUE TITLE
Closing QR popup scrolls the page on Chrome

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/teloscan#625]
**Describe the bug**
After closing the QR code popup on the address page, the page suffers a not-wanted scroll down. This only happens on Chrome

**To Reproduce**
1. Go to this [address page](https://teloscan-redesign-mainnet.netlify.app/address/0xA39DeA47e01ECd7A9826a1115aB58F9a11733B60)
2. Click on the QR icon
3. Close the popup
4. Notice the page scrolls down

**Expected behavior**
The page should remain in the same place

**Screenshots**
![image](https://github.com/telosnetwork/teloscan/assets/4420760/42fc9b06-3422-4e63-8025-7f349c32fdc1)

**Device**
 - Browser Chrome
 - Windows

**Comment by pmjanus** [comment]
Still wonky but not closed after partial fix, just priority lowered.
