### ISSUE TITLE
On write contract tab changes to code tab after logging in or out

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/teloscan#640]
**Describe the bug**
If you are in the Contract page on the write section, you will notice that you have a "connect wallet" button if you are not logged or you will see a little button with your address in cesa you being logged already. Either case, if you login or logout using that button, the tab will change to code when you're done.

**To Reproduce**
1. Go to [this contract page](https://beta.teloscan.io/address/0xf85bA8be4E5B82da25D68970b03F4FEBefD6Fa98?tab=contract)
2. Click on write tab
3. Log in / Log out
4. See tab changes to code

**Expected behavior**
The tab Write should stay selected

[FIXED HERE](https://github.com/telosnetwork/teloscan/pull/774)

**Screenshots**
![image](https://github.com/telosnetwork/teloscan/assets/4420760/2dbcbbb8-e74c-4006-9583-f9b4fe351436)
![image](https://github.com/telosnetwork/teloscan/assets/4420760/51aae913-6990-42bc-ad96-9d6fc716f347)
![image](https://github.com/telosnetwork/teloscan/assets/4420760/1b6b1115-51a5-4eea-ae4d-316e27efa672)

**Comment by rozzaswap** [comment]
Tested successfully and approved PR to dev.
