### ISSUE TITLE
Restore IN/OUT fields on Transaction table

### ISSUE THREAD

**Issue by iht76** [telosnetwork/teloscan#657]
Any particular reason you got rid of the IN/OUT fields (from deploy-preview-368)  in beta.teloscan.io? Imo, it is nice having them, as it makes it easier to navigate through bunch of transactions when you are looking for something. Anyways, the new version looks and feels very good!

**Comment by pmjanus** [comment]
https://www.teloscan.io/address/0xc96afc666A4195366a46E4ca8C4f10f3C39Ee363 example
