### ISSUE TITLE
BUG: Testnet, searching for an incorrect TX Hash doesn't produce an error

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/teloscan#66]
**Describe the bug**
Searching for an incorrect transaction hash, does not produce an error message. Hash is changed in detail view, but the same data is present.

**To Reproduce**
1: Open any transaction.
2: Change one of the bits ie. a with b
3: Observe that the same data is present, whereas the TX hash is changed.
4: Searching for the invalid hash in a new query windoe or through the URL produce the correct behavior.

**Expected behavior**
Produce an error.

**Screenshots**
Alter a bit.
![Screenshot 2022-03-28 at 23 18 24](https://user-images.githubusercontent.com/74211870/160488894-6a46a891-e7c7-4e40-81c8-1900a6fb2c19.png)

![Screenshot 2022-03-28 at 23 18 16](https://user-images.githubusercontent.com/74211870/160488973-cf35be4c-354e-4220-931f-776ee9895051.png)

![Screenshot 2022-03-28 at 23 17 53](https://user-images.githubusercontent.com/74211870/160489023-72702841-4df1-4d92-8e54-ef00479e06c7.png)

**Desktop**
 - OS: OSX
 - Browser:

**Comment by poplexity** [comment]
Fixed, can you confirm on testnet @DestinyDevTeam

**Comment by DestinyDevTeam** [comment]
Tested, and Working as expected.
