### ISSUE TITLE
Redesign Day 2 bugs

### ISSUE THREAD

**Issue by rozzaswap** [telosnetwork/teloscan#669]
- [x] Token balance missing from token list 
- [x] Show token grid not working
- [x] Internal Transactions showing ALL transactions
- [x] fix that not verified contracts are not shown as such
- [x] add the native explorer link (maybe in the "more" menu)
- [x] add the name of the verified contracts, the previous version had it and at least for me it is useful :)
- [x] french footer looks broken

**Comment by rozzaswap** [comment]
### Token balance missing from token list 

Token in token list missing from token list, see 0x5367E5809E33bFf31dCa0C4Ef60386c34Edd6a87 - SLUSH token

![Image](https://github.com/telosnetwork/teloscan/assets/105747830/7780a1b8-15e8-4942-9db4-a19bf7b7c460)

![Image](https://github.com/telosnetwork/teloscan/assets/105747830/5b0171f5-cd45-4d47-8d81-ee91e454da4b)

**Comment by rozzaswap** [comment]
### Show token grid not working

<img width="873" alt="image" src="https://github.com/telosnetwork/teloscan/assets/105747830/480d06df-55ad-42d7-afdb-2b1f82561c93">

**Comment by Viterbo** [comment]
French footer has no translation strings 

![image](https://github.com/telosnetwork/teloscan/assets/4420760/32cabda8-e5c5-46ab-9e5f-0bd65d1d308e)
