### ISSUE TITLE
Show token name instead of contract name

### ISSUE THREAD

**Issue by rozzaswap** [telosnetwork/teloscan#671]
In the tokens list, the token symbol should be displayed instead of the contract name.

For example, the POPS token is displayed as AnyswapV6ERC20

![Image](https://github.com/telosnetwork/teloscan/assets/105747830/4015487d-8cfb-4b5e-871e-19a63b8acf0a)

![Image](https://github.com/telosnetwork/teloscan/assets/105747830/04c1d43c-736e-49cb-a0d7-f1346a40a611)

**Comment by Viterbo** [comment]
@rozzaswap 

We are already displaying the symbol and the name of the contract. Do you want me to change this?
However, there are some tokens that are not showing the symbols for some reason. I can check that and fix it if possible.

![image](https://github.com/telosnetwork/teloscan/assets/4420760/91a571e3-201f-4654-8806-743ce4dc5374)
