### ISSUE TITLE
BUG: Testnet, Possible to connect invalid address through MetaMask

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/teloscan#68]
**Describe the bug**
Connecting Wallet switches network, but Mainnet Address is approved.
Looking up the address will result in an error as the address is not created on Testnet.

**To Reproduce**
1: Click Connect
2: Login to MetaMask
3: Select a Mainnet Address
4: Approve
5: Click on View Address

**Expected Behaviour**
Should not be able to connect an invalid address

**Environment Used**
OS: OSX
Browser: Chrome
Wallet: MetaMask extension for Chrome

**Comment by poplexity** [comment]
Fixed, doing the network switch BEFORE we let the user login.

**Comment by DestinyDevTeam** [comment]
Working as expected. Tested on OSX and Chrome with the Chrome Extension for MetaMask.
