### ISSUE TITLE
Enhancement: Testnet, aspect ratio of Native Wallet Wombat seems wrong

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/teloscan#69]
**Description**
Wombat Logo is blurry

**Reproduce**
1: Click Connect
2: Select Native Wallet

**Expected Behavior**
Clear Logo of accepted Wallets

![Screenshot 2022-03-28 at 23 39 59](https://user-images.githubusercontent.com/74211870/160492104-75c36e7b-43ff-4924-9e42-a1d41c26723f.png)

**Environment Used**
OS: OSX
Browser: Chrome

**Comment by DonaldPeat** [comment]
@DestinyDevTeam  this is what is coming back from the api for their icon, i've noticed it elsewhere as well.

**Comment by DestinyDevTeam** [comment]
Looks better now, I guess this is what we get from that image source.
