### ISSUE TITLE
Internal transactions page incorrect number of rows in table.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#834]
**Describe the bug**
On the internal transactions page https://www.teloscan.io/txsinternal the table does not return the number of rows indicated on the records per page control: 

**To Reproduce**
1. Go to https://www.teloscan.io/txsinternal on testnet or mainnet
2. verify that the number of records doesnt match the amount of records selected
3. go to other pages, it is the same case

**Expected behavior**
The number of rows selected should be the number of rows shown (if available records).

**Screenshots**
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/2b08ba37-5a70-479e-a02b-295d10342bee">

**Comment by Viterbo** [comment]
This issue is taken care of in [this PR](https://github.com/telosnetwork/teloscan/pull/813) which is ready to go, waiting for the 1.2.3 version of the indexer to be deployed. So, I will close this issue.
