### ISSUE TITLE
Fix text alignment on wallet selection.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#836]
**Describe the bug**
<img width="315" alt="image" src="https://github.com/user-attachments/assets/9bcc10e0-8d35-4195-b8c1-98e9b8d67f61">

Align the text for wallet connect, verify alignment on supported sizes.

**Comment by yato-sketch** [comment]
I think, this issue already resolved.

**Comment by Viterbo** [comment]
Yes, it is. I close this issue
![image](https://github.com/user-attachments/assets/2373644a-27ba-4892-a088-fac532bc82fd)
